### ISSUE TITLE
Introduce the portion package to handle intervals

### ISSUE THREAD

**Issue by nelimee** [tqec/tqec#266]
#256 introduced the `Interval` and `Intervals` classes to represent portions of R, all the real numbers. It turns out that a Python package seem to implement exactly that.

> LGTM. Just wanted to mention that, I found a package [`portion`](https://github.com/AlexandreDecan/portion?tab=readme-ov-file#interval-operations) that appear to do something similar to `Interval`.
> 
> _Originally posted by @inmzhang in https://github.com/QCHackers/tqec/pull/256#pullrequestreview-2195298205_

            
The question is then: "is it worth using that package?".

At first glance I am on the "yes" side, but here are a few points (on both sides) that might help making the best decision:

- the `portion` package seems well maintained,
- using an external package allow us to support less code in `tqec`,
- using an external package would increase the time needed to fix a bug and the friction to implement new features,

Any thoughts?

**Comment by pranshiusc** [comment]
Hi, I would like to work on this issue. I have forked the repository, will be working on this one.
