### ISSUE TITLE
Tracking issue for `tqec.circuit.detectors`

### ISSUE THREAD

**Issue by nelimee** [tqec/tqec#389]
This is a tracking issue for several improvements that may be added to the `tqec.circuit.detectors`.

First, an organizational question:

- [x] tqec/tqec#390

Then, a few issues describing potential improvements to the `tqec.circuit.detectors` package:

- [x] tqec/tqec#407
- [ ] tqec/tqecd#2
- [ ] tqec/tqecd#1
- [ ] Test thoroughly `tqec.circuit.detectors`

The 3 issues above are somewhat disjoint from the first issue listed here that ask whether or not we should have a dedicated GitHub organization to the `tqec` library and sub-libraries (`tqec.circuit.detectors` being the first sub-library).

**Comment by Gistbatch** [comment]
See also #399

**Comment by Gistbatch** [comment]
Do you think detector computation should be a seperate repository? Maybe it's a good idea to have something like `qiskit`, where performance-critical parts can be implemented in rust.

**Comment by nelimee** [comment]
> Do you think detector computation should be a seperate repository? Maybe it's a good idea to have something like `qiskit`, where performance-critical parts can be implemented in rust.

For the, the content of `tqec.circuit.detectors` should be in a separate repository, and has been thought from the beginning as a standalone and self-contained portion of `tqec` for that specific reason. On the contrary, I do not think that the code in `tqec.compile.detectors` should be in its own repository, as it is too tightly linked to the other `tqec` modules (circuit generation from `Template`/`Plaquettes` in particular).

**Comment by nelimee** [comment]
This issue should be closed alongside #407 as all the other issues tracked will be opened in the newly created `tqec/tqecd` repository.

**Comment by nelimee** [comment]
Once #409 is merged, all issues related to `tqecd` will be on https://github.com/tqec/tqecd, and so this issue does not have sense anymore.
