### ISSUE TITLE
Should we move the `tqec` package to its own GitHub organization?

### ISSUE THREAD

**Issue by nelimee** [tqec/tqec#390]
With #378, I think it is the right moment to ask the question about whether we keep the `tqec` package (and sub-packages that might spin-off from it, `tqec.circuit.detectors` being a good example) in the QCHackers organization or not. 

In most of the non company-backed open-source repositories that I have seen, once the repository starts to gain some traction, there is a move to extract the repository from its original organization (or user) and create a dedicated GitHub organization to manage the repository.

This issue is here to discuss about the pros and cons of such a move, to ultimately decide what is the best move for the future.

**Comment by inmzhang** [comment]
It's always confusing to me why `tqec` package is in the QCHackers organization. All the other packages seem not relevant to the field of QEC. So in my opinion, it's better to have a new organization for `tqec` and its subpackages.

**Comment by afowler** [comment]
I support moving.

**Comment by inmzhang** [comment]
Closing this as the movement has been completed.
