### ISSUE TITLE
Invalid Links

### ISSUE THREAD

**Issue by Gistbatch** [tqec/tqec#397]
## Describe the bug
After the move to this new repository, the links to the docs are no longer valid.
It seems that also some pages of the docs have invalid links.
## Steps to reproduce the behavior:
1. Visit the repository on GitHub and click the links

**Comment by nelimee** [comment]
> @nelimee I'm not sure if the permissions for this repo are set up correctly. I cannot assign myself nor any labels.

I just sent you an invitation to the `tqec` organization. Once accepted, you should be able to do such things. If not, please tell me :)

---------

About this issue, it will be fixed at the first PR merged. I will see if I can trigger a re-generation of the documentation.

**Comment by Gistbatch** [comment]
I think it's still not possible to assign anything

**Comment by inmzhang** [comment]
> I think it's still not possible to assign anything

Hi Philipp, I have changed the base permission for the tqec members from `read` to `write`. Could you try again?

**Comment by Gistbatch** [comment]
It's working now. Should people outside of the organization also be able to self-assign issues (as in #399)

**Comment by inmzhang** [comment]
> It's working now. Should people outside of the organization also be able to self-assign issues (as in https://github.com/tqec/tqec/issues/399)

I don't think there is a setting for this?

**Comment by Gistbatch** [comment]
I'm also not sure. In #400, I get a permission error when triggering the pipeline:
```
  /usr/bin/git push origin gh-pages
  remote: Permission to tqec/tqec.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/tqec/tqec.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
```
and 
```
Run marocchino/sticky-pull-request-comment@v2
Error: Resource not accessible by integration
```

**Comment by nelimee** [comment]
As explained in #400 this is due to security issues with granting write access to the repository to anyone from the outside via GitHub actions. I will take a little bit of time to double-check the organisation/repository permissions, and try to fix this GitHub action problem.

**Comment by Gistbatch** [comment]
Thanks! I was confused; the checks on #381 are complete, so I wondered if the issues stem from me triggering the pipeline.

**Comment by Gistbatch** [comment]
> About this issue, it will be fixed at the first PR merged. I will see if I can trigger a re-generation of the documentation.
This is still not the case after the last merge, I hope this will work once #381 is merged.

**Comment by nelimee** [comment]
All the links are now valid thanks to #381. Closing.
