### ISSUE TITLE
Try to fix GitHub CI pemissions

### ISSUE THREAD

**Issue by nelimee** [tqec/tqec#401]
## Describe the bug
There are currently two actions in the CI that require write permission to the repository in order to work correctly: the documentation generation and the coverage report generation.

## Steps to reproduce the behavior:
See CI on #400.

## Expected behavior
The CI should not be failing on expected missing permissions. We should either:

- fix the CI to work even when the PR is from a branch outside of the `tqec` repository.
- let the actions requiring write permission fail silently.

**Comment by JLenssen** [comment]
### Options

1. Related discussion about this error in `peaceiris/actions-gh-pages`: https://github.com/peaceiris/actions-gh-pages/issues/1102, where they recommend to change permissions.
2. We could use [`continue-on-error` ](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) a job can then still pass.

I can create a PR for the second one, if that's what you prefer.

**Comment by nelimee** [comment]
> ### Options
> 
>     1. Related discussion about this error in `peaceiris/actions-gh-pages`: [support:  unable to access 'https://github.com/saigkill/SaschasToolbox.git/': The requested URL returned error: 403 peaceiris/actions-gh-pages#1102](https://github.com/peaceiris/actions-gh-pages/issues/1102), where they recommend to change permissions.
> 
>     2. We could use [`continue-on-error` ](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) a job can then still pass.
> 
> 
> I can create a PR for the second one, if that's what you prefer.

Option number 1 is not the reason, the current permission is read/write (like in the screen shown). It is due to the fact that branches from external contributors (i.e., not from the `tqec` repository) are considered potentially insecure and are not given the write permission. `continue_on_error` seems like a good solution, you can create a PR :) Also, try to create it from your own account (which should be your only option as you should not have the right to create a branch in `tqec/tqec`) to test live.
