### ISSUE TITLE
Create plaquette from RPNG string

### ISSUE THREAD

**Issue by giangiac** [tqec/tqec#410]
As discussed on 12/04, we decided to describe the plaquettes with a 16 character string (and 3 spaces).
See below for a description of the format.

We need to have a function to validate the RPNG string and a function that generate the plaquette given the RPNG string.

----

**Example of a RPNG string and description of the format:**

```
-z1- -z2- -z3- -z4-
rpng rpng rpng rpng
```

(r) data qubit reset basis or h or -  
(p) data basis for the controlled operation (x means CNOT controlled on the ancilla and targeting the data qubit, y means CY, z means CZ)  
(n) time step (positive integers, all distinct, typically in 1-5)  
(g) data qubit measure basis or h or -

Assumptions on the circuit:
- if not otherwise stated, a basis can be {x,y,z}
- the ancilla is always initialized in $\ket{+}$ and measured in the X basis
- the ancilla is always the control qubit for the CNOT, CY, or CZ gates

**Comment by giangiac** [comment]
I started working on this new feature in my fork (branch `feature/generate-plaquette-from-rpng`):
https://github.com/giangiac/tqec/tree/feature/generate-plaquette-from-rpng

**Comment by nelimee** [comment]
> I started working on this new feature in my fork (branch `feature/generate-plaquette-from-rpng`): https://github.com/giangiac/tqec/tree/feature/generate-plaquette-from-rpng

Could you open a PR in order for everyone to see what's happening?

**Comment by nelimee** [comment]
Also note that it would be nice to have a generic and documented interface, so that users will be able to implement their own translation if they want.
