### ISSUE TITLE
Introduce `RPNGTemplate`

### ISSUE THREAD

**Issue by nelimee** [tqec/tqec#412]
**Is your feature request related to a problem? Please describe.**

Following the last discussion during our weekly meeting, we reached the conclusion that `Template` should not return indices anymore, mostly due to #386. Instead, integer indices should be replaced by RPNG⁴ textual representation that is able to accurately and concisely describe the plaquette that is expected at each entry of the `Template.instantiate` output.

**Describe the solution you'd like**

There are two potential solution I can see:

1. change the output of `Template.instantiate` to a 2-dimensional array of RPNG⁴ strings (or any data-structure representing such string, that might be introduced in #411),
2. do not touch anything on the `Template` implementation, but make `tqec.templates` an implementation detail (and consequently a private or semi-private module) and use it to implement a ""`RPNGTemplate`"" (name to be refined). This would basically follow the idea proposed in #386.

I personally prefer solution number 2 as it allows to re-use the solid, well tested and well understood `tqec.templates` implementation as a foundation, and it seems "simple". Basically, an ""`RPNGTemplate`"" could be implemented like:

```py
from dataclasses import dataclass
from enum import Enum
from typing import Literal, Mapping

from tqec.templates.base import Template


class BasisEnum(Enum):
    X = "X"
    Y = "Y"
    Z = "Z"


@dataclass
class RPNG:
    r: BasisEnum | None
    p: BasisEnum | None
    n: int | None
    g: BasisEnum | Literal["H"] | None


@dataclass
class RPNGPlaquette:
    corners: tuple[RPNG, RPNG, RPNG, RPNG]


@dataclass
class RPNGTemplate:
    template: Template
    mapping: Mapping[int, RPNGPlaquette]

    def instantiate(self, k: int) -> list[list[RPNGPlaquette]]:
        indices = self.template.instantiate(k)
        return [[self.mapping[i] for i in row] for row in indices]
```

The advantages of such an approach would be the following:

- Scaling would still be handled by the `Template` approach that has proven to be quite robust and well tested.
- We could re-use the `QubitTemplate` for most of the `RPNGTemplate` instances of interest, and keep the number of templates implemented as low as possible. This is nice because implementing correctly a `Template` is error-prone and time-consuming.
- It is a relatively small change.

Any remark/question/alternative ways?

**Comment by afowler** [comment]
I like the below proposal.

**Comment by Gistbatch** [comment]
I think the second approach is better. If we realize `Templates` don't fit the approach we can still change this later. I think this will also make implementing #387 easier.
