### ISSUE TITLE
Create a `RPNGTemplate` library

### ISSUE THREAD

**Issue by nelimee** [tqec/tqec#416]
Issue #412 should:

- make the previously widely used `tqec.templates.template.Template` base class an implementation detail,
- expose a new API (called `RPNGTemplate` in #412 but that name might change) that is basically the same as `Template` except that `instantiate` now returns a 2-dimensional array of `RPNG⁴` strings (or `RGN - RPNG⁴`, see #411).

Once #412 will be merged with the new API, we will have to create a few instances of `RPNGTemplate` in order to be able to use them on concrete examples. 

As an example, if the example API in #412 is the final one, below is the implementation of the regular logical qubit
![image](https://github.com/user-attachments/assets/717685cd-64c6-4ada-a15a-4ac73b570917)
performing a memory experiment:

```py
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Literal, Mapping

from tqec.plaquette.frozendefaultdict import FrozenDefaultDict
from tqec.templates.base import Template
from tqec.templates.qubit import QubitTemplate

# Defined in #411 
class BasisEnum(Enum):
    X = "X"
    Y = "Y"
    Z = "Z"

# Defined in #411 
@dataclass
class RPNG:
    r: BasisEnum | None
    p: BasisEnum | None
    n: int | None
    g: BasisEnum | Literal["H"] | None

# Defined in #411
@dataclass
class RPNGPlaquette:
    corners: tuple[RPNG, RPNG, RPNG, RPNG]

    @staticmethod
    def from_string(repr: str) -> RPNGPlaquette: ...

# Defined in #412
@dataclass
class RPNGTemplate:
    template: Template
    mapping: Mapping[int, RPNGPlaquette]

    def instantiate(self, k: int) -> list[list[RPNGPlaquette]]:
        indices = self.template.instantiate(k)
        return [[self.mapping[i] for i in row] for row in indices]


empty_plaquette = RPNGPlaquette.from_string("--- ---- ---- ---- ----")

logical_qubit_memory = RPNGTemplate(
    template=QubitTemplate(),
    mapping=FrozenDefaultDict(
        {
            6: RPNGPlaquette.from_string("xx5 ---- ---- -x3- -x4-"),  # XX_UP
            7: RPNGPlaquette.from_string("xx5 ---- -z3- ---- -z4-"),  # ZZ_LEFT
            9: RPNGPlaquette.from_string("xx5 -x1- -x2- -x3- -x4-"),  # XXXX
            10: RPNGPlaquette.from_string("xx5 -z1- -z3- -z2- -z4-"),  # ZZZZ
            12: RPNGPlaquette.from_string("xx5 -z1- ---- -z2- ----"),  # ZZ_RIGHT
            13: RPNGPlaquette.from_string("xx5 -x1- -x2- ---- ----"),  # XX_DOWN
        },
        default_factory=lambda: empty_plaquette,
    ),
)
```

The above code is only pseudo-code! #411 and #412 might change the actual implementation details, API or class names.

This issue is about using what has been defined in #411 and then in #412 to build usable `RPNGTemplate` instances.

**Comment by afowler** [comment]
How necessary do you think the initial xx5 is? In my mind this could be
dropped, but I'm curious to hear your thoughts as to why you feel it's
important to include.

Best,
Austin.

**Comment by nelimee** [comment]
> How necessary do you think the initial xx5 is? 

In my opinion, the `n` (which is `5` here) is counter-productive as it gives the impression to the user that he/she will have control on when the measurement happens, which is not really the case because measurement will likely be grouped into a unique time slice depending on what is happening on other parts of the chip. The `rp` part is interesting as it gives more freedom, but absolutely not necessary.

Hence, I agree with the view that the initial `xx5` part is likely not interesting to include.
